FROM mcr.microsoft.com/dotnet/aspnet:8.0
# Set the working directory
WORKDIR /app
# Copy the published output to the container
COPY ./build/service-linux-x64 .
EXPOSE 22345
# Start the application
ENTRYPOINT ["dotnet", "UZonMailService.dll"]