/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncTooltip: typeof import('./src/components/asyncTooltip/AsyncTooltip.vue')['default']
    CancelBtn: typeof import('./src/components/componentWrapper/buttons/CancelBtn.vue')['default']
    CancleBtn: typeof import('./src/components/componentWrapper/buttons/CancleBtn.vue')['default']
    ConfirmBtn: typeof import('./src/components/componentWrapper/buttons/ConfirmBtn.vue')['default']
    ContextMen: typeof import('./src/components/contextMenu/ContextMen.vue')['default']
    ContextMenu: typeof import('./src/components/contextMenu/ContextMenu.vue')['default']
    ContextMenuIndex: typeof import('./src/components/contextMenu/ContextMenuIndex.vue')['default']
    CreateBtn: typeof import('./src/components/componentWrapper/buttons/CreateBtn.vue')['default']
    DeleteBtn: typeof import('./src/components/componentWrapper/buttons/DeleteBtn.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    LowCodeForm: typeof import('./src/components/popupDialog/lowCodeForm.vue')['default']
    OkBtn: typeof import('./src/components/componentWrapper/buttons/OkBtn.vue')['default']
    QTablePro: typeof import('./src/components/componentWrapper/QTablePro.vue')['default']
    QTableSelf: typeof import('./src/components/componentWrapper/QTableSelf.vue')['default']
    QTableWrapper: typeof import('./src/components/componentWrapper/QTableWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UzonTable: typeof import('./src/components/componentWrapper/UzonTable.vue')['default']
  }
}
