services:
  uzon-mail-dev:
    container_name: uzon-mail-dev
    image: node:20.11.0
    volumes:
      - ./:/app/uzon-mail
    working_dir: /app/uzon-mail
    ports:
      - 9000:9000
    init: true
    command: [ "sh", "-c", "exec sleep infinity" ]
